//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heading
    {
        public int ID { get; set; }
        public string Introduction { get; set; }
        public string Skills { get; set; }
        public string Skills2 { get; set; }
        public string Skills3 { get; set; }
        public string Description { get; set; }
    }
}
