//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public int ID { get; set; }
        public string Heading { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string GitHubLink { get; set; }
        public string Class { get; set; }
        public string DataId { get; set; }
        public string DataType { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
